# Generated by Django 4.2.7 on 2023-11-15 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_parent_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='teaching_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.class'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teaching_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.class'),
        ),
    ]
